"use client";

import { Loader2, RefreshCw, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { SectionCard } from "../section-card";
import { useGenerateInsight, useLeadInsight } from "@/hooks/use-ai";
import { ApiError } from "@/lib/api-error";
import { RECOMMENDED_SERVICE_LABELS } from "@/lib/ai-types";

export function AiInsightSection({ leadId }: { leadId: string }) {
  const { data, isLoading } = useLeadInsight(leadId);
  const generate = useGenerateInsight(leadId);
  const insight = data?.insight ?? null;

  function handleGenerate() {
    generate.mutate(undefined, {
      onError: (error) => {
        toast.error(error instanceof ApiError ? error.message : "Couldn't generate the AI insight");
      },
    });
  }

  const busy = generate.isPending;

  return (
    <SectionCard
      title="AI Insight"
      icon={Sparkles}
      action={
        <Button variant="outline" size="sm" onClick={handleGenerate} disabled={busy} className="gap-1.5">
          {busy ? <Loader2 className="size-3.5 animate-spin" /> : <RefreshCw className="size-3.5" />}
          {insight ? "Regenerate" : "Generate"}
        </Button>
      }
    >
      {isLoading ? (
        <p className="text-sm text-muted-foreground">Loading…</p>
      ) : !insight ? (
        <p className="text-sm text-muted-foreground italic">
          No AI insight generated yet — built only from this lead&apos;s verified audit data, never
          invented.
        </p>
      ) : (
        <div className="flex flex-col gap-3">
          <p className="text-sm font-medium">{insight.summary}</p>
          <p className="text-sm text-muted-foreground">{insight.growthAnalysis}</p>

          {insight.recommendedServices.length > 0 && (
            <div>
              <p className="mb-1.5 text-xs font-medium text-muted-foreground">Recommended services</p>
              <div className="flex flex-wrap gap-1.5">
                {insight.recommendedServices.map((service) => (
                  <Badge key={service} variant="secondary">
                    {RECOMMENDED_SERVICE_LABELS[service]}
                  </Badge>
                ))}
              </div>
            </div>
          )}

          <p className="text-xs text-muted-foreground/70">
            Generated by {insight.providerMode.toLowerCase()} ({insight.model}) ·{" "}
            {new Date(insight.generatedAt).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" })}
          </p>
        </div>
      )}
    </SectionCard>
  );
}
